//! `cargo xtask homebrew-formula`: render the `retsu-ai/homebrew-qq` formula
//! for one release from its `SHA256SUMS`.
//!
//! The release workflow runs this after publishing and pushes the output as
//! `Formula/qq.rb` to the tap repository. The formula is generated, never
//! hand-edited: every field comes from the version and the checksum file the
//! release produced, so the tap can only describe archives that exist.

use std::{
    collections::HashMap,
    io::{self, Write},
    path::PathBuf,
};

use clap::Args;
use thiserror::Error;

use crate::release::Version;

#[derive(Debug, Args)]
pub struct HomebrewArgs {
    /// Release version, e.g. `0.2.0`; must match the `SHA256SUMS` filenames.
    #[arg(long)]
    version: String,
    /// Path to the release's `SHA256SUMS` (`<hex>  <archive>` per line).
    #[arg(long)]
    sums: PathBuf,
}

#[derive(Debug, Error)]
pub enum HomebrewError {
    #[error("{0:?} is not a plain MAJOR.MINOR.PATCH version")]
    InvalidVersion(String),
    #[error("failed to read {path}")]
    Read {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("SHA256SUMS line {line} is not `<sha256 hex>  <filename>`: {text:?}")]
    MalformedLine { line: usize, text: String },
    #[error("SHA256SUMS has no entry for {0}; the release is missing that build")]
    MissingArchive(String),
    #[error("failed to write the formula")]
    Write(#[source] io::Error),
}

/// The four archives Homebrew can install, in the order the formula lists
/// them. Windows is not a Homebrew platform.
const TARGETS: [(&str, &str, &str); 4] = [
    ("on_macos", "on_arm", "aarch64-apple-darwin"),
    ("on_macos", "on_intel", "x86_64-apple-darwin"),
    ("on_linux", "on_arm", "aarch64-unknown-linux-musl"),
    ("on_linux", "on_intel", "x86_64-unknown-linux-musl"),
];

pub fn run(args: HomebrewArgs) -> Result<(), HomebrewError> {
    let version =
        Version::parse(&args.version).ok_or(HomebrewError::InvalidVersion(args.version))?;
    let sums = std::fs::read_to_string(&args.sums).map_err(|source| HomebrewError::Read {
        path: args.sums.clone(),
        source,
    })?;
    let formula = render_formula(version, &sums)?;
    let mut stdout = io::stdout().lock();
    stdout
        .write_all(formula.as_bytes())
        .and_then(|()| stdout.flush())
        .map_err(HomebrewError::Write)
}

/// Parses `sha256sum`-style lines. The Windows archive is hashed on a runner
/// whose `sha256sum` marks binary mode with `*`, so the marker is stripped.
fn parse_sums(sums: &str) -> Result<HashMap<&str, &str>, HomebrewError> {
    let mut entries = HashMap::new();
    for (index, line) in sums.lines().enumerate() {
        let text = line.trim();
        if text.is_empty() {
            continue;
        }
        let (hex, name) = match text.split_once(char::is_whitespace) {
            Some(parts) => parts,
            None => {
                return Err(HomebrewError::MalformedLine {
                    line: index + 1,
                    text: text.to_owned(),
                });
            }
        };
        let name = name.trim_start().trim_start_matches('*');
        if hex.len() != 64 || !hex.bytes().all(|byte| byte.is_ascii_hexdigit()) || name.is_empty() {
            return Err(HomebrewError::MalformedLine {
                line: index + 1,
                text: text.to_owned(),
            });
        }
        entries.insert(name, hex);
    }
    Ok(entries)
}

pub fn render_formula(version: Version, sums: &str) -> Result<String, HomebrewError> {
    let entries = parse_sums(sums)?;
    let mut out = String::with_capacity(1024);
    out.push_str("# Generated by `cargo xtask homebrew-formula`; do not edit by hand.\n");
    out.push_str("class Qq < Formula\n");
    out.push_str("  desc \"AI coding agents in one binary\"\n");
    out.push_str("  homepage \"https://github.com/retsu-AI/qq\"\n");
    out.push_str(&format!("  version \"{version}\"\n"));
    out.push_str("  license \"MIT\"\n");

    let mut open_os: Option<&str> = None;
    for (os, arch, target) in TARGETS {
        if open_os != Some(os) {
            if open_os.is_some() {
                out.push_str("  end\n");
            }
            out.push_str(&format!("\n  {os} do\n"));
            open_os = Some(os);
        }
        let archive = format!("qq-v{version}-{target}.tar.gz");
        let Some(sha256) = entries.get(archive.as_str()) else {
            return Err(HomebrewError::MissingArchive(archive));
        };
        out.push_str(&format!("    {arch} do\n"));
        out.push_str(&format!(
            "      url \"https://github.com/retsu-AI/qq/releases/download/v{version}/{archive}\"\n"
        ));
        out.push_str(&format!("      sha256 \"{sha256}\"\n"));
        out.push_str("    end\n");
    }
    if open_os.is_some() {
        out.push_str("  end\n");
    }

    out.push_str("\n  def install\n    bin.install \"qq\"\n  end\n");
    out.push_str(
        "\n  test do\n    assert_match version.to_s, shell_output(\"#{bin}/qq --version\")\n  end\n",
    );
    out.push_str("end\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SUMS: &str = "\
92d47a2872cd914f669fe25b42e44c7a6653c455d6dc1a4792464dc991751280  qq-v0.1.3-aarch64-apple-darwin.tar.gz
0a7364f084a59e2c521abb830024f4280c7435d9182e45490b99e693c956bdf2  qq-v0.1.3-aarch64-unknown-linux-musl.tar.gz
924becc6b3ab0504d8a86ce7c6cc5b3d3d8510b61fdf24bdcafa3eda89d850d5  qq-v0.1.3-x86_64-apple-darwin.tar.gz
b12a6316e4e8472fdf09d1b0350ead515a2ace96fa565ab4a89996f5ed34a79a *qq-v0.1.3-x86_64-pc-windows-msvc.zip
649af539223c81693ebb89fe4eba0e94558e90477d48c4a66170ab3dff7a497a  qq-v0.1.3-x86_64-unknown-linux-musl.tar.gz
";

    #[test]
    fn renders_every_homebrew_platform_from_the_release_sums() {
        let formula = render_formula(Version::parse("0.1.3").unwrap(), SUMS).unwrap();
        let expected = "\
# Generated by `cargo xtask homebrew-formula`; do not edit by hand.
class Qq < Formula
  desc \"AI coding agents in one binary\"
  homepage \"https://github.com/retsu-AI/qq\"
  version \"0.1.3\"
  license \"MIT\"

  on_macos do
    on_arm do
      url \"https://github.com/retsu-AI/qq/releases/download/v0.1.3/qq-v0.1.3-aarch64-apple-darwin.tar.gz\"
      sha256 \"92d47a2872cd914f669fe25b42e44c7a6653c455d6dc1a4792464dc991751280\"
    end
    on_intel do
      url \"https://github.com/retsu-AI/qq/releases/download/v0.1.3/qq-v0.1.3-x86_64-apple-darwin.tar.gz\"
      sha256 \"924becc6b3ab0504d8a86ce7c6cc5b3d3d8510b61fdf24bdcafa3eda89d850d5\"
    end
  end

  on_linux do
    on_arm do
      url \"https://github.com/retsu-AI/qq/releases/download/v0.1.3/qq-v0.1.3-aarch64-unknown-linux-musl.tar.gz\"
      sha256 \"0a7364f084a59e2c521abb830024f4280c7435d9182e45490b99e693c956bdf2\"
    end
    on_intel do
      url \"https://github.com/retsu-AI/qq/releases/download/v0.1.3/qq-v0.1.3-x86_64-unknown-linux-musl.tar.gz\"
      sha256 \"649af539223c81693ebb89fe4eba0e94558e90477d48c4a66170ab3dff7a497a\"
    end
  end

  def install
    bin.install \"qq\"
  end

  test do
    assert_match version.to_s, shell_output(\"#{bin}/qq --version\")
  end
end
";
        assert_eq!(formula, expected);
    }

    #[test]
    fn refuses_a_release_missing_a_homebrew_platform() {
        let partial = SUMS
            .lines()
            .filter(|line| !line.contains("x86_64-apple-darwin"))
            .collect::<Vec<_>>()
            .join("\n");
        let error = render_formula(Version::parse("0.1.3").unwrap(), &partial).unwrap_err();
        assert!(
            matches!(&error, HomebrewError::MissingArchive(name) if name == "qq-v0.1.3-x86_64-apple-darwin.tar.gz"),
            "{error}"
        );
    }

    #[test]
    fn refuses_sums_for_a_different_version() {
        let error = render_formula(Version::parse("0.2.0").unwrap(), SUMS).unwrap_err();
        assert!(matches!(error, HomebrewError::MissingArchive(_)), "{error}");
    }

    #[test]
    fn rejects_malformed_checksum_lines() {
        for (text, line) in [
            ("nothex  qq-v0.1.3-aarch64-apple-darwin.tar.gz\n", 1),
            (
                "92d47a2872cd914f669fe25b42e44c7a6653c455d6dc1a4792464dc991751280\n",
                1,
            ),
            (
                "\n92d47a2872cd914f669fe25b42e44c7a6653c455d6dc1a4792464dc99175128  short.tar.gz\n",
                2,
            ),
        ] {
            let error = render_formula(Version::parse("0.1.3").unwrap(), text).unwrap_err();
            assert!(
                matches!(&error, HomebrewError::MalformedLine { line: found, .. } if *found == line),
                "{text:?}: {error}"
            );
        }
    }
}
