[package]
name = "spike-leptos"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
spike-common.workspace = true
qq-client.workspace = true
qq-protocol.workspace = true
leptos = { version = "0.8", features = ["csr"] }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
