//! `CHANGELOG.md` generation for `cargo xtask release`: Conventional Commit
//! subjects since the newest `v*` tag, grouped into a dated section that is
//! prepended to the file.

use std::{
    path::Path,
    process::{Command as ProcessCommand, Stdio},
};

use super::{ReleaseError, Version};

pub(super) const FILE_NAME: &str = "CHANGELOG.md";

const HEADER: &str = "# Changelog\n\nGenerated by `cargo xtask release` from the Conventional Commit \
                      subjects merged since the previous release; edit the commits, not this file.\n";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Section {
    Features,
    Fixes,
    Performance,
    Other,
}

impl Section {
    const ALL: [Self; 4] = [Self::Features, Self::Fixes, Self::Performance, Self::Other];

    const fn title(self) -> &'static str {
        match self {
            Self::Features => "Features",
            Self::Fixes => "Fixes",
            Self::Performance => "Performance",
            Self::Other => "Other",
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
struct Entry {
    section: Section,
    breaking: bool,
    scope: Option<String>,
    summary: String,
}

/// Parses `type(scope)!: summary (#N)`. A subject outside the grammar is
/// still listed, under Other, verbatim: a release must not silently lose a
/// commit because its message was misspelled. `chore(release):` bumps are the
/// one subject dropped, because they are the release itself.
fn parse_subject(subject: &str) -> Option<Entry> {
    let subject = subject.trim();
    if subject.is_empty() {
        return None;
    }
    let Some((head, summary)) = subject.split_once(": ") else {
        return Some(Entry {
            section: Section::Other,
            breaking: false,
            scope: None,
            summary: subject.to_owned(),
        });
    };
    let (head, breaking) = match head.strip_suffix('!') {
        Some(head) => (head, true),
        None => (head, false),
    };
    let (kind, scope) = match head.split_once('(') {
        Some((kind, rest)) => match rest.strip_suffix(')') {
            Some(scope) if !scope.is_empty() => (kind, Some(scope)),
            Some(_) | None => (head, None),
        },
        None => (head, None),
    };
    let conventional = !kind.is_empty()
        && kind
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit());
    if !conventional {
        return Some(Entry {
            section: Section::Other,
            breaking: false,
            scope: None,
            summary: subject.to_owned(),
        });
    }
    if kind == "chore" && scope == Some("release") {
        return None;
    }
    let section = match kind {
        "feat" => Section::Features,
        "fix" => Section::Fixes,
        "perf" => Section::Performance,
        _ => Section::Other,
    };
    Some(Entry {
        section,
        breaking,
        scope: scope.map(str::to_owned),
        summary: summary.trim().to_owned(),
    })
}

/// The `## X.Y.Z — date` section for `subjects`, newest commit first within
/// each group, empty groups omitted.
pub(super) fn render_section(version: Version, date: &str, subjects: &[String]) -> String {
    let entries: Vec<Entry> = subjects
        .iter()
        .filter_map(|subject| parse_subject(subject))
        .collect();
    let mut out = format!("## {version} — {date}\n");
    for section in Section::ALL {
        let mut rows = entries.iter().filter(|entry| entry.section == section);
        let Some(first) = rows.next() else {
            continue;
        };
        out.push_str(&format!("\n### {}\n", section.title()));
        for entry in std::iter::once(first).chain(rows) {
            out.push_str("- ");
            if entry.breaking {
                out.push_str("**breaking:** ");
            }
            if let Some(scope) = &entry.scope {
                out.push_str(scope);
                out.push_str(": ");
            }
            out.push_str(&entry.summary);
            out.push('\n');
        }
    }
    out
}

/// `existing` with `section` inserted above the first release heading, or
/// after the header when the file has no releases yet, or a fresh file.
pub(super) fn prepend_section(existing: Option<&str>, section: &str) -> String {
    let Some(existing) = existing else {
        return format!("{HEADER}\n{section}");
    };
    let mut offset = 0;
    for line in existing.split_inclusive('\n') {
        if line.starts_with("## ") {
            let (head, tail) = existing.split_at(offset);
            return format!("{head}{section}\n{tail}");
        }
        offset += line.len();
    }
    let separator = if existing.ends_with('\n') {
        "\n"
    } else {
        "\n\n"
    };
    format!("{existing}{separator}{section}")
}

/// Commit subjects after the newest `v*` tag (every commit when there is
/// none), newest first, merges excluded.
pub(super) fn subjects_since_last_tag(root: &Path) -> Result<Vec<String>, ReleaseError> {
    let tags = git_stdout(root, &["tag", "--list", "v*"])?;
    let newest = tags
        .lines()
        .filter_map(|tag| Version::parse(tag.trim().strip_prefix('v')?))
        .max();
    let range = match newest {
        Some(version) => format!("v{version}..HEAD"),
        None => "HEAD".to_owned(),
    };
    let log = git_stdout(root, &["log", &range, "--format=%s", "--no-merges"])?;
    Ok(log
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(str::to_owned)
        .collect())
}

pub(super) fn today_utc() -> String {
    let now = time::OffsetDateTime::now_utc();
    format!(
        "{:04}-{:02}-{:02}",
        now.year(),
        u8::from(now.month()),
        now.day()
    )
}

fn git_stdout(root: &Path, args: &[&str]) -> Result<String, ReleaseError> {
    let output = ProcessCommand::new("git")
        .args(args)
        .current_dir(root)
        .stderr(Stdio::inherit())
        .output()
        .map_err(|source| ReleaseError::Launch {
            program: "git",
            source,
        })?;
    if !output.status.success() {
        return Err(ReleaseError::Failed {
            program: "git",
            args: args.join(" "),
            status: output.status,
        });
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn subjects(list: &[&str]) -> Vec<String> {
        list.iter().map(|s| (*s).to_owned()).collect()
    }

    #[test]
    fn groups_conventional_subjects_and_keeps_pr_numbers() {
        let version = Version::parse("0.2.0").unwrap();
        let rendered = render_section(
            version,
            "2026-09-24",
            &subjects(&[
                "chore(release): v0.2.0",
                "feat(provider): add compiled provider cache (#123)",
                "fix(runtime): preserve session context (#124)",
                "feat(protocol)!: replace the event envelope (#125)",
                "perf: trim startup allocations (#126)",
                "docs(guide): explain trust (#127)",
                "Merge branch fixup",
                "refactor(tui): split the composer",
            ]),
        );
        assert_eq!(
            rendered,
            "## 0.2.0 — 2026-09-24\n\
             \n### Features\n\
             - provider: add compiled provider cache (#123)\n\
             - **breaking:** protocol: replace the event envelope (#125)\n\
             \n### Fixes\n\
             - runtime: preserve session context (#124)\n\
             \n### Performance\n\
             - trim startup allocations (#126)\n\
             \n### Other\n\
             - guide: explain trust (#127)\n\
             - Merge branch fixup\n\
             - tui: split the composer\n"
        );
    }

    #[test]
    fn omits_empty_sections_and_release_bumps() {
        let rendered = render_section(
            Version::parse("0.1.1").unwrap(),
            "2026-01-02",
            &subjects(&["chore(release): v0.1.1", "fix: one thing (#9)", "  "]),
        );
        assert_eq!(
            rendered,
            "## 0.1.1 — 2026-01-02\n\n### Fixes\n- one thing (#9)\n"
        );
        assert_eq!(
            render_section(Version::parse("0.1.2").unwrap(), "d", &[]),
            "## 0.1.2 — d\n"
        );
    }

    #[test]
    fn subjects_outside_the_grammar_land_in_other_verbatim() {
        for raw in [
            "Fix typo: in prose",
            "feat(: broken",
            "feat(): empty scope",
            "WIP",
        ] {
            let entry = parse_subject(raw).unwrap();
            assert_eq!(entry.section, Section::Other, "{raw}");
            assert_eq!(entry.summary, raw);
            assert_eq!(entry.scope, None);
            assert!(!entry.breaking);
        }
        assert_eq!(parse_subject("chore(release): v9.9.9"), None);
        assert_eq!(parse_subject(""), None);
        // A release-scoped commit of another type is still news.
        assert!(parse_subject("fix(release): tag the right commit").is_some());
    }

    #[test]
    fn prepends_above_the_newest_release_and_creates_the_file() {
        let section = "## 0.2.0 — d\n\n### Fixes\n- x\n";
        let fresh = prepend_section(None, section);
        assert!(fresh.starts_with("# Changelog\n\nGenerated by `cargo xtask release`"));
        assert!(
            fresh.ends_with("\n\n## 0.2.0 — d\n\n### Fixes\n- x\n"),
            "{fresh:?}"
        );

        let existing = "# Changelog\n\nintro\n\n## 0.1.0 — c\n\n### Other\n- y\n";
        assert_eq!(
            prepend_section(Some(existing), section),
            "# Changelog\n\nintro\n\n## 0.2.0 — d\n\n### Fixes\n- x\n\n## 0.1.0 — c\n\n### Other\n- y\n"
        );
        assert_eq!(
            prepend_section(Some("# Changelog\n"), section),
            "# Changelog\n\n## 0.2.0 — d\n\n### Fixes\n- x\n"
        );
        assert_eq!(
            prepend_section(Some("# Changelog"), section),
            "# Changelog\n\n## 0.2.0 — d\n\n### Fixes\n- x\n"
        );
    }

    #[test]
    fn today_is_an_iso_date() {
        let today = today_utc();
        assert_eq!(today.len(), 10, "{today}");
        assert_eq!(today.as_bytes()[4], b'-');
        assert_eq!(today.as_bytes()[7], b'-');
    }
}
